# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - run: pnpm ci
      - run: pnpm run lint -- --ext .js
